{% set version = "0.2.3" %}

package:
    name: datapoint-python
    version: {{version}}

source:
    # git_url: https://github.com/jacobtomlinson/datapoint-python.git
    # git_rev: v{{version}}
    path: .

build:
    script: python setup.py install
    number: 1

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - requests #==2.3.0
        - appdirs  # Currently available in channel "faph"
        - pytz

test:
    imports:
        - datapoint
    requires:
        - nose
        - pylint <1.4 # [py26]
        - pylint # [not py26]
    commands:
        - pylint -E datapoint
        - nosetests -w  $RECIPE_DIR/tests/unit
        # Integration tests need the API_KEY


about:
    home: https://github.com/jacobtomlinson/datapoint-python
    license: TBC