import datetime

EXPECTED_FIRST_HOURLY_TIMESTEP = {
    "time": datetime.datetime(2024, 2, 15, 19, 0, tzinfo=datetime.timezone.utc),
    "screenTemperature": {
        "value": 11.0,
        "description": "Screen Air Temperature",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "maxScreenAirTemp": {
        "value": 11.55,
        "description": "Maximum Screen Air Temperature Over Previous Hour",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "minScreenAirTemp": {
        "value": 10.98,
        "description": "Minimum Screen Air Temperature Over Previous Hour",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "screenDewPointTemperature": {
        "value": 8.94,
        "description": "Screen Dew Point Temperature",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "feelsLikeTemperature": {
        "value": 10.87,
        "description": "Feels Like Temperature",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "windSpeed10m": {
        "value": 1.18,
        "description": "10m Wind Speed",
        "unit_name": "metres per second",
        "unit_symbol": "m/s",
    },
    "windDirectionFrom10m": {
        "value": 180,
        "description": "10m Wind From Direction",
        "unit_name": "degrees",
        "unit_symbol": "deg",
    },
    "windGustSpeed10m": {
        "value": 6.69,
        "description": "10m Wind Gust Speed",
        "unit_name": "metres per second",
        "unit_symbol": "m/s",
    },
    "max10mWindGust": {
        "value": 8.92,
        "description": "Maximum 10m Wind Gust Speed Over Previous Hour",
        "unit_name": "metres per second",
        "unit_symbol": "m/s",
    },
    "visibility": {
        "value": 19174,
        "description": "Visibility",
        "unit_name": "metres",
        "unit_symbol": "m",
    },
    "screenRelativeHumidity": {
        "value": 86.99,
        "description": "Screen Relative Humidity",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "mslp": {
        "value": 100660,
        "description": "Mean Sea Level Pressure",
        "unit_name": "pascals",
        "unit_symbol": "Pa",
    },
    "uvIndex": {
        "value": 0,
        "description": "UV Index",
        "unit_name": "dimensionless",
        "unit_symbol": "1",
    },
    "significantWeatherCode": {
        "value": "Partly cloudy",
        "description": "Significant Weather Code",
        "unit_name": "dimensionless",
        "unit_symbol": "1",
    },
    "precipitationRate": {
        "value": 0.0,
        "description": "Precipitation Rate",
        "unit_name": "millimetres per hour",
        "unit_symbol": "mm/h",
    },
    "totalPrecipAmount": {
        "value": 0.0,
        "description": "Total Precipitation Amount Over Previous Hour",
        "unit_name": "millimetres",
        "unit_symbol": "mm",
    },
    "totalSnowAmount": {
        "value": 0,
        "description": "Total Snow Amount Over Previous Hour",
        "unit_name": "millimetres",
        "unit_symbol": "mm",
    },
    "probOfPrecipitation": {
        "value": 4,
        "description": "Probability of Precipitation",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
}

EXPECTED_AT_DATETIME_HOURLY_TIMESTEP = {
    "time": datetime.datetime(2024, 2, 16, 19, 0, tzinfo=datetime.timezone.utc),
    "screenTemperature": {
        "value": 8.94,
        "description": "Screen Air Temperature",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "maxScreenAirTemp": {
        "value": 9.6,
        "description": "Maximum Screen Air Temperature Over Previous Hour",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "minScreenAirTemp": {
        "value": 8.9,
        "description": "Minimum Screen Air Temperature Over Previous Hour",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "screenDewPointTemperature": {
        "value": 6.8,
        "description": "Screen Dew Point Temperature",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "feelsLikeTemperature": {
        "value": 7.68,
        "description": "Feels Like Temperature",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "windSpeed10m": {
        "value": 2.46,
        "description": "10m Wind Speed",
        "unit_name": "metres per second",
        "unit_symbol": "m/s",
    },
    "windDirectionFrom10m": {
        "value": 255,
        "description": "10m Wind From Direction",
        "unit_name": "degrees",
        "unit_symbol": "deg",
    },
    "windGustSpeed10m": {
        "value": 7.35,
        "description": "10m Wind Gust Speed",
        "unit_name": "metres per second",
        "unit_symbol": "m/s",
    },
    "max10mWindGust": {
        "value": 8.02,
        "description": "Maximum 10m Wind Gust Speed Over Previous Hour",
        "unit_name": "metres per second",
        "unit_symbol": "m/s",
    },
    "visibility": {
        "value": 22767,
        "description": "Visibility",
        "unit_name": "metres",
        "unit_symbol": "m",
    },
    "screenRelativeHumidity": {
        "value": 86.81,
        "description": "Screen Relative Humidity",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "mslp": {
        "value": 102246,
        "description": "Mean Sea Level Pressure",
        "unit_name": "pascals",
        "unit_symbol": "Pa",
    },
    "uvIndex": {
        "value": 0,
        "description": "UV Index",
        "unit_name": "dimensionless",
        "unit_symbol": "1",
    },
    "significantWeatherCode": {
        "value": "Clear night",
        "description": "Significant Weather Code",
        "unit_name": "dimensionless",
        "unit_symbol": "1",
    },
    "precipitationRate": {
        "value": 0.0,
        "description": "Precipitation Rate",
        "unit_name": "millimetres per hour",
        "unit_symbol": "mm/h",
    },
    "totalPrecipAmount": {
        "value": 0.0,
        "description": "Total Precipitation Amount Over Previous Hour",
        "unit_name": "millimetres",
        "unit_symbol": "mm",
    },
    "totalSnowAmount": {
        "value": 0,
        "description": "Total Snow Amount Over Previous Hour",
        "unit_name": "millimetres",
        "unit_symbol": "mm",
    },
    "probOfPrecipitation": {
        "value": 0,
        "description": "Probability of Precipitation",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
}

EXPECTED_AT_DATETIME_HOURLY_FINAL_TIMESTEP = {
    "time": datetime.datetime(2024, 2, 17, 19, 0, tzinfo=datetime.timezone.utc),
    "screenTemperature": {
        "value": 10.34,
        "description": "Screen Air Temperature",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "screenDewPointTemperature": {
        "value": 9.37,
        "description": "Screen Dew Point Temperature",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "feelsLikeTemperature": {
        "value": 8.34,
        "description": "Feels Like Temperature",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "windSpeed10m": {
        "value": 4.29,
        "description": "10m Wind Speed",
        "unit_name": "metres per second",
        "unit_symbol": "m/s",
    },
    "windDirectionFrom10m": {
        "value": 187,
        "description": "10m Wind From Direction",
        "unit_name": "degrees",
        "unit_symbol": "deg",
    },
    "windGustSpeed10m": {
        "value": 8.68,
        "description": "10m Wind Gust Speed",
        "unit_name": "metres per second",
        "unit_symbol": "m/s",
    },
    "visibility": {
        "value": 10128,
        "description": "Visibility",
        "unit_name": "metres",
        "unit_symbol": "m",
    },
    "screenRelativeHumidity": {
        "value": 94.17,
        "description": "Screen Relative Humidity",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "mslp": {
        "value": 102910,
        "description": "Mean Sea Level Pressure",
        "unit_name": "pascals",
        "unit_symbol": "Pa",
    },
    "uvIndex": {
        "value": 0,
        "description": "UV Index",
        "unit_name": "dimensionless",
        "unit_symbol": "1",
    },
    "significantWeatherCode": {
        "value": "Overcast",
        "description": "Significant Weather Code",
        "unit_name": "dimensionless",
        "unit_symbol": "1",
    },
    "precipitationRate": {
        "value": 0.0,
        "description": "Precipitation Rate",
        "unit_name": "millimetres per hour",
        "unit_symbol": "mm/h",
    },
    "probOfPrecipitation": {
        "value": 16,
        "description": "Probability of Precipitation",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
}
EXPECTED_FIRST_DAILY_TIMESTEP = {
    "time": datetime.datetime(2024, 2, 16, 0, 0, tzinfo=datetime.timezone.utc),
    "10MWindSpeed": {
        "value": 1.39,
        "description": "10m Wind Speed at Local Midnight",
        "unit_name": "metres per second",
        "unit_symbol": "m/s",
    },
    "10MWindDirection": {
        "value": 243,
        "description": "10m Wind Direction at Local Midnight",
        "unit_name": "degrees",
        "unit_symbol": "deg",
    },
    "10MWindGust": {
        "value": 7.2,
        "description": "10m Wind Gust Speed at Local Midnight",
        "unit_name": "metres per second",
        "unit_symbol": "m/s",
    },
    "Visibility": {
        "value": 27712,
        "description": "Visibility at Local Midnight",
        "unit_name": "metres",
        "unit_symbol": "m",
    },
    "RelativeHumidity": {
        "value": 80.91,
        "description": "Relative Humidity at Local Midnight",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "Mslp": {
        "value": 102640,
        "description": "Mean Sea Level Pressure at Local Midnight",
        "unit_name": "pascals",
        "unit_symbol": "Pa",
    },
    "SignificantWeatherCode": {
        "value": 7,
        "description": "Night Significant Weather Code",
        "unit_name": "dimensionless",
        "unit_symbol": "1",
    },
    "MinScreenTemperature": {
        "value": 5.32,
        "description": "Night Minimum Screen Air Temperature",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "UpperBoundMinTemp": {
        "value": 9.17,
        "description": "Upper Bound on Night Minimum Screen Air Temperature",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "LowerBoundMinTemp": {
        "value": 3.56,
        "description": "Lower Bound on Night Minimum Screen Air Temperature",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "MinFeelsLikeTemp": {
        "value": 6.27,
        "description": "Night Minimum Feels Like Air Temperature",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "UpperBoundMinFeelsLikeTemp": {
        "value": 8.74,
        "description": "Upper Bound on Night Minimum Feels Like Air Temperature",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "LowerBoundMinFeelsLikeTemp": {
        "value": 2.75,
        "description": "Lower Bound on Night Minimum Feels Like Air Temperature",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "ProbabilityOfPrecipitation": {
        "value": 11,
        "description": "Probability of Precipitation During The Night",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "ProbabilityOfSnow": {
        "value": 0,
        "description": "Probability of Snow During The Night",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "ProbabilityOfHeavySnow": {
        "value": 0,
        "description": "Probability of Heavy Snow During The Night",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "ProbabilityOfRain": {
        "value": 10,
        "description": "Probability of Rain During The Night",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "ProbabilityOfHeavyRain": {
        "value": 0,
        "description": "Probability of Heavy Rain During The Night",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "ProbabilityOfHail": {
        "value": 0,
        "description": "Probability of Hail During The Night",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "ProbabilityOfSferics": {
        "value": 0,
        "description": "Probability of Sferics During The Night",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
}

EXPECTED_AT_DATETIME_DAILY_TIMESTEP = {
    "time": datetime.datetime(2024, 2, 17, 0, 0, tzinfo=datetime.timezone.utc),
    "10MWindSpeed": {
        "value": 6.1,
        "description": "10m Wind Speed at Local Midnight",
        "unit_name": "metres per second",
        "unit_symbol": "m/s",
    },
    "10MWindDirection": {
        "value": 218,
        "description": "10m Wind Direction at Local Midnight",
        "unit_name": "degrees",
        "unit_symbol": "deg",
    },
    "10MWindGust": {
        "value": 12.98,
        "description": "10m Wind Gust Speed at Local Midnight",
        "unit_name": "metres per second",
        "unit_symbol": "m/s",
    },
    "Visibility": {
        "value": 5915,
        "description": "Visibility at Local Midnight",
        "unit_name": "metres",
        "unit_symbol": "m",
    },
    "RelativeHumidity": {
        "value": 93.62,
        "description": "Relative Humidity at Local Midnight",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "Mslp": {
        "value": 102800,
        "description": "Mean Sea Level Pressure at Local Midnight",
        "unit_name": "pascals",
        "unit_symbol": "Pa",
    },
    "SignificantWeatherCode": {
        "value": 15,
        "description": "Night Significant Weather Code",
        "unit_name": "dimensionless",
        "unit_symbol": "1",
    },
    "MinScreenTemperature": {
        "value": 9.96,
        "description": "Night Minimum Screen Air Temperature",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "UpperBoundMinTemp": {
        "value": 10.71,
        "description": "Upper Bound on Night Minimum Screen Air Temperature",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "LowerBoundMinTemp": {
        "value": 9.04,
        "description": "Lower Bound on Night Minimum Screen Air Temperature",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "MinFeelsLikeTemp": {
        "value": 7.76,
        "description": "Night Minimum Feels Like Air Temperature",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "UpperBoundMinFeelsLikeTemp": {
        "value": 8.28,
        "description": "Upper Bound on Night Minimum Feels Like Air Temperature",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "LowerBoundMinFeelsLikeTemp": {
        "value": 7.04,
        "description": "Lower Bound on Night Minimum Feels Like Air Temperature",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "ProbabilityOfPrecipitation": {
        "value": 97,
        "description": "Probability of Precipitation During The Night",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "ProbabilityOfSnow": {
        "value": 0,
        "description": "Probability of Snow During The Night",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "ProbabilityOfHeavySnow": {
        "value": 0,
        "description": "Probability of Heavy Snow During The Night",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "ProbabilityOfRain": {
        "value": 97,
        "description": "Probability of Rain During The Night",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "ProbabilityOfHeavyRain": {
        "value": 96,
        "description": "Probability of Heavy Rain During The Night",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "ProbabilityOfHail": {
        "value": 20,
        "description": "Probability of Hail During The Night",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "ProbabilityOfSferics": {
        "value": 10,
        "description": "Probability of Sferics During The Night",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
}
EXPECTED_AT_DATETIME_DAILY_FINAL_TIMESTEP = {
    "time": datetime.datetime(2024, 2, 23, 12, 0, tzinfo=datetime.timezone.utc),
    "10MWindSpeed": {
        "value": 7.11,
        "description": "10m Wind Speed at Local Midday",
        "unit_name": "metres per second",
        "unit_symbol": "m/s",
    },
    "10MWindDirection": {
        "value": 231,
        "description": "10m Wind Direction at Local Midday",
        "unit_name": "degrees",
        "unit_symbol": "deg",
    },
    "10MWindGust": {
        "value": 13.38,
        "description": "10m Wind Gust Speed at Local Midday",
        "unit_name": "metres per second",
        "unit_symbol": "m/s",
    },
    "Visibility": {
        "value": 23049,
        "description": "Visibility at Local Midday",
        "unit_name": "metres",
        "unit_symbol": "m",
    },
    "RelativeHumidity": {
        "value": 73.25,
        "description": "Relative Humidity at Local Midday",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "Mslp": {
        "value": 98974,
        "description": "Mean Sea Level Pressure at Local Midday",
        "unit_name": "pascals",
        "unit_symbol": "Pa",
    },
    "maxUvIndex": {
        "value": 2,
        "description": "Day Maximum UV Index",
        "unit_name": "dimensionless",
        "unit_symbol": "1",
    },
    "SignificantWeatherCode": {
        "value": 10,
        "description": "Day Significant Weather Code",
        "unit_name": "dimensionless",
        "unit_symbol": "1",
    },
    "MaxScreenTemperature": {
        "value": 8.57,
        "description": "Day Maximum Screen Air Temperature",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "UpperBoundMaxTemp": {
        "value": 10.67,
        "description": "Upper Bound on Day Maximum Screen Air Temperature",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "LowerBoundMaxTemp": {
        "value": 6.67,
        "description": "Lower Bound on Day Maximum Screen Air Temperature",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "MaxFeelsLikeTemp": {
        "value": 4.42,
        "description": "Day Maximum Feels Like Air Temperature",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "UpperBoundMaxFeelsLikeTemp": {
        "value": 7.38,
        "description": "Upper Bound on Day Maximum Feels Like Air Temperature",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "LowerBoundMaxFeelsLikeTemp": {
        "value": 3.89,
        "description": "Lower Bound on Day Maximum Feels Like Air Temperature",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "ProbabilityOfPrecipitation": {
        "value": 52,
        "description": "Probability of Precipitation During The Day",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "ProbabilityOfSnow": {
        "value": 0,
        "description": "Probability of Snow During The Day",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "ProbabilityOfHeavySnow": {
        "value": 0,
        "description": "Probability of Heavy Snow During The Day",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "ProbabilityOfRain": {
        "value": 52,
        "description": "Probability of Rain During The Day",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "ProbabilityOfHeavyRain": {
        "value": 48,
        "description": "Probability of Heavy Rain During The Day",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "ProbabilityOfHail": {
        "value": 10,
        "description": "Probability of Hail During The Day",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "ProbabilityOfSferics": {
        "value": 11,
        "description": "Probability of Sferics During The Day",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
}

EXPECTED_FIRST_THREE_HOURLY_TIMESTEP = {
    "time": datetime.datetime(2024, 2, 17, 15, 0, tzinfo=datetime.timezone.utc),
    "maxScreenAirTemp": {
        "value": 12.0,
        "description": "Maximum Screen Air Temperature Over Previous Three Hours",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "minScreenAirTemp": {
        "value": 10.73,
        "description": "Minimum Screen Air Temperature Over Previous Three Hours",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "max10mWindGust": {
        "value": 8.87,
        "description": "Maximum 10m Wind Gust Speed Over Previous Three Hours",
        "unit_name": "metres per second",
        "unit_symbol": "m/s",
    },
    "significantWeatherCode": {
        "value": "Overcast",
        "description": "Three Hour Significant Weather Code",
        "unit_name": "dimensionless",
        "unit_symbol": "1",
    },
    "totalPrecipAmount": {
        "value": 0.0,
        "description": "Total Precipitation Amount Over Previous Three Hours",
        "unit_name": "millimetres",
        "unit_symbol": "mm",
    },
    "totalSnowAmount": {
        "value": 0,
        "description": "Total Snow Amount Over Previous Three Hours",
        "unit_name": "millimetres",
        "unit_symbol": "mm",
    },
    "windSpeed10m": {
        "value": 5.04,
        "description": "10m Wind Speed Over Previous Three Hours",
        "unit_name": "metres per second",
        "unit_symbol": "m/s",
    },
    "windDirectionFrom10m": {
        "value": 225,
        "description": "10m Wind From Direction Over Previous Three Hours",
        "unit_name": "degrees",
        "unit_symbol": "deg",
    },
    "windGustSpeed10m": {
        "value": 8.75,
        "description": "10m Wind Gust Speed Over Previous Three Hours",
        "unit_name": "metres per second",
        "unit_symbol": "m/s",
    },
    "visibility": {
        "value": 9118,
        "description": "Visibility Over Previous Three Hours",
        "unit_name": "metres",
        "unit_symbol": "m",
    },
    "mslp": {
        "value": 103090,
        "description": "Mean Sea Level Pressure Over Previous Three Hours",
        "unit_name": "pascals",
        "unit_symbol": "Pa",
    },
    "screenRelativeHumidity": {
        "value": 96.84,
        "description": "Screen Relative Humidity Over Previous Three Hours",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "feelsLikeTemp": {
        "value": 8.53,
        "description": "Feels Like Temperature Over Previous Three Hours",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "uvIndex": {
        "value": 1,
        "description": "Maximum UV Index Over Previous Three Hours",
        "unit_name": "dimensionless",
        "unit_symbol": "1",
    },
    "probOfPrecipitation": {
        "value": 10,
        "description": "Three Hour Probability of Precipitation",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "probOfSnow": {
        "value": 0,
        "description": "Three Hour Probability of Snow",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "probOfHeavySnow": {
        "value": 0,
        "description": "Three Hour Probability of Heavy Snow",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "probOfRain": {
        "value": 10,
        "description": "Three Hour Probability of Rain",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "probOfHeavyRain": {
        "value": 0,
        "description": "Three Hour Probability of Heavy Rain",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "probOfHail": {
        "value": 0,
        "description": "Three Hour Probability of Hail",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "probOfSferics": {
        "value": 0,
        "description": "Three Hour Probability of Sferics",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
}

EXPECTED_AT_DATETIME_THREE_HOURLY_TIMESTEP = {
    "time": datetime.datetime(2024, 2, 22, 18, 0, tzinfo=datetime.timezone.utc),
    "maxScreenAirTemp": {
        "value": 9.82,
        "description": "Maximum Screen Air Temperature Over Previous Three Hours",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "minScreenAirTemp": {
        "value": 7.61,
        "description": "Minimum Screen Air Temperature Over Previous Three Hours",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "max10mWindGust": {
        "value": 19.28,
        "description": "Maximum 10m Wind Gust Speed Over Previous Three Hours",
        "unit_name": "metres per second",
        "unit_symbol": "m/s",
    },
    "significantWeatherCode": {
        "value": "Light rain shower",
        "description": "Three Hour Significant Weather Code",
        "unit_name": "dimensionless",
        "unit_symbol": "1",
    },
    "totalPrecipAmount": {
        "value": 1.11,
        "description": "Total Precipitation Amount Over Previous Three Hours",
        "unit_name": "millimetres",
        "unit_symbol": "mm",
    },
    "totalSnowAmount": {
        "value": 0,
        "description": "Total Snow Amount Over Previous Three Hours",
        "unit_name": "millimetres",
        "unit_symbol": "mm",
    },
    "windSpeed10m": {
        "value": 7.91,
        "description": "10m Wind Speed Over Previous Three Hours",
        "unit_name": "metres per second",
        "unit_symbol": "m/s",
    },
    "windDirectionFrom10m": {
        "value": 239,
        "description": "10m Wind From Direction Over Previous Three Hours",
        "unit_name": "degrees",
        "unit_symbol": "deg",
    },
    "windGustSpeed10m": {
        "value": 14.42,
        "description": "10m Wind Gust Speed Over Previous Three Hours",
        "unit_name": "metres per second",
        "unit_symbol": "m/s",
    },
    "visibility": {
        "value": 20148,
        "description": "Visibility Over Previous Three Hours",
        "unit_name": "metres",
        "unit_symbol": "m",
    },
    "mslp": {
        "value": 98434,
        "description": "Mean Sea Level Pressure Over Previous Three Hours",
        "unit_name": "pascals",
        "unit_symbol": "Pa",
    },
    "screenRelativeHumidity": {
        "value": 79.36,
        "description": "Screen Relative Humidity Over Previous Three Hours",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "feelsLikeTemp": {
        "value": 3.74,
        "description": "Feels Like Temperature Over Previous Three Hours",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "uvIndex": {
        "value": 0,
        "description": "Maximum UV Index Over Previous Three Hours",
        "unit_name": "dimensionless",
        "unit_symbol": "1",
    },
    "probOfPrecipitation": {
        "value": 44,
        "description": "Three Hour Probability of Precipitation",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "probOfSnow": {
        "value": 0,
        "description": "Three Hour Probability of Snow",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "probOfHeavySnow": {
        "value": 0,
        "description": "Three Hour Probability of Heavy Snow",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "probOfRain": {
        "value": 44,
        "description": "Three Hour Probability of Rain",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "probOfHeavyRain": {
        "value": 32,
        "description": "Three Hour Probability of Heavy Rain",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "probOfHail": {
        "value": 4,
        "description": "Three Hour Probability of Hail",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "probOfSferics": {
        "value": 6,
        "description": "Three Hour Probability of Sferics",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
}

EXPECTED_AT_DATETIME_THREE_HOURLY_FINAL_TIMESTEP = {
    "time": datetime.datetime(2024, 2, 24, 15, 0, tzinfo=datetime.timezone.utc),
    "maxScreenAirTemp": {
        "value": 8.25,
        "description": "Maximum Screen Air Temperature Over Previous Three Hours",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "minScreenAirTemp": {
        "value": 7.96,
        "description": "Minimum Screen Air Temperature Over Previous Three Hours",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "max10mWindGust": {
        "value": 12.77,
        "description": "Maximum 10m Wind Gust Speed Over Previous Three Hours",
        "unit_name": "metres per second",
        "unit_symbol": "m/s",
    },
    "significantWeatherCode": {
        "value": "Light rain shower",
        "description": "Three Hour Significant Weather Code",
        "unit_name": "dimensionless",
        "unit_symbol": "1",
    },
    "totalPrecipAmount": {
        "value": 0.58,
        "description": "Total Precipitation Amount Over Previous Three Hours",
        "unit_name": "millimetres",
        "unit_symbol": "mm",
    },
    "totalSnowAmount": {
        "value": 0,
        "description": "Total Snow Amount Over Previous Three Hours",
        "unit_name": "millimetres",
        "unit_symbol": "mm",
    },
    "windSpeed10m": {
        "value": 5.98,
        "description": "10m Wind Speed Over Previous Three Hours",
        "unit_name": "metres per second",
        "unit_symbol": "m/s",
    },
    "windDirectionFrom10m": {
        "value": 228,
        "description": "10m Wind From Direction Over Previous Three Hours",
        "unit_name": "degrees",
        "unit_symbol": "deg",
    },
    "windGustSpeed10m": {
        "value": 11.48,
        "description": "10m Wind Gust Speed Over Previous Three Hours",
        "unit_name": "metres per second",
        "unit_symbol": "m/s",
    },
    "visibility": {
        "value": 22483,
        "description": "Visibility Over Previous Three Hours",
        "unit_name": "metres",
        "unit_symbol": "m",
    },
    "mslp": {
        "value": 99725,
        "description": "Mean Sea Level Pressure Over Previous Three Hours",
        "unit_name": "pascals",
        "unit_symbol": "Pa",
    },
    "screenRelativeHumidity": {
        "value": 72.01,
        "description": "Screen Relative Humidity Over Previous Three Hours",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "feelsLikeTemp": {
        "value": 4.97,
        "description": "Feels Like Temperature Over Previous Three Hours",
        "unit_name": "degrees Celsius",
        "unit_symbol": "Cel",
    },
    "uvIndex": {
        "value": 1,
        "description": "Maximum UV Index Over Previous Three Hours",
        "unit_name": "dimensionless",
        "unit_symbol": "1",
    },
    "probOfPrecipitation": {
        "value": 32,
        "description": "Three Hour Probability of Precipitation",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "probOfSnow": {
        "value": 0,
        "description": "Three Hour Probability of Snow",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "probOfHeavySnow": {
        "value": 0,
        "description": "Three Hour Probability of Heavy Snow",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "probOfRain": {
        "value": 32,
        "description": "Three Hour Probability of Rain",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "probOfHeavyRain": {
        "value": 17,
        "description": "Three Hour Probability of Heavy Rain",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "probOfHail": {
        "value": 1,
        "description": "Three Hour Probability of Hail",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
    "probOfSferics": {
        "value": 3,
        "description": "Three Hour Probability of Sferics",
        "unit_name": "percentage",
        "unit_symbol": "%",
    },
}
